# Generated by Django 5.0.5 on 2025-06-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="media/")),
                ("price_band", models.CharField(max_length=50)),
                ("opening_date", models.DateField()),
                ("closing_date", models.DateField()),
                ("issue_size", models.CharField(max_length=100)),
                ("issue_type", models.CharField(max_length=100)),
                ("listing_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Upcoming", "Upcoming"),
                            ("Closed", "Closed"),
                            ("Listed", "Listed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ipo_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "listing_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "listing_gain",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "current_market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "current_return",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("rhp_pdf", models.FileField(blank=True, null=True, upload_to="pdfs/")),
                (
                    "drhp_pdf",
                    models.FileField(blank=True, null=True, upload_to="pdfs/"),
                ),
            ],
        ),
    ]
