# Generated by Django 5.0.5 on 2025-06-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipo",
            name="status",
            field=models.CharField(
                choices=[
                    ("Upcoming", "Upcoming"),
                    ("Closed", "Closed"),
                    ("Listed", "Listed"),
                    ("Ongoing", "Ongoing"),
                ],
                max_length=20,
            ),
        ),
    ]
