# Generated by Django 5.0.5 on 2025-06-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipo_app", "0002_alter_ipo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipo",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
