# Generated by Django 5.0.5 on 2025-06-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipo_app", "0003_alter_ipo_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipo",
            name="drhp_pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/drhp/"),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="rhp_pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/rhp/"),
        ),
    ]
